### ISSUE TITLE
CERT wycofał wersję v1

### ISSUE THREAD

**Issue by krystian3w** [FiltersHeroes/KAD#2590]
### Bloker (Blocker)

uBo 1.64.1b1

### Link bezpośredni, na którym występuje problem

```markdown
https://github.com
```

### Opis błędu

https://cert.pl/posts/2025/01/wycofanie-pierwszej-wersji-listy/

```yml
TimeoutError: [Errno 110] Connection timed out

nurllib3.exceptions.MaxRetryError: 
  HTTPSConnectionPool(host='hole.cert.pl', port=443): 
     Max retries exceeded with url: /domains/v2/domains.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f34e31a77d0>, 'Connection to hole.cert.pl timed out. (connect timeout=None)'))
```

### Dodatkowe informacje mogące mieć znaczenie

> _[/wycofanie-pierwszej-wersji-listy](https://cert.pl/posts/2025/01/wycofanie-pierwszej-wersji-listy/)_

- Być może wystarczy to olać (zadziała przekierowanie 301 i najwyżej nic nie usuniemy w ten sposób) lub cofnąć jakiś stary commit np. https://github.com/FiltersHeroes/KAD/commit/a3b3a6c77f43beb75da9967e9dc476e80516711d (mniej sprawdzania przez skrypt, jakie straci sens w czerwcu),

- być może da się użyć plików actions_202x.log (może logu nie czyszczą ze staroci), jako zamiennik starego pliku json, do cofania unbanów bez rozdzielania certu na osobny plik (gdy wersja v2 nie będzie wpisywać dalej daty po 180 dniach kwarantanny, a kasować cały rekord dla zmniejszenia rozmiaru pliku).

> ```yml
> TimeoutError: [Errno 110] Connection timed out
> ```

- Na błąd przekroczenia czasu być może trzeba by robić mirror/cdn lub wymuszać łączenie inną drogą do CERT (być może CLI MS lub społeczność uBo MV2 przegięła pałkę i CLI lub crawlery dostali 🍌),
  - Opcjonalnie aktualizacja w akcjach z pomięciem CERT (czyli sprawdzeniem nowości LWS i tylko sortowaniem do momentu aż ktoś będzie mieć dostęp by z własnego komputera zrobić pełną aktualizację z nowościami CERT lub "pełne" (to co bot uznał za martwe) czyszczenie CERT z wpisaniem staroci do pliku "wygasłe" (tak by nie cofać się na CircleCI lub obciążać tym GitLab jak oni nie mają banana 🍌 lub lepszy czas dostępu)).
